### ISSUE TITLE
"TM" text in header is a different font from the rest of the text

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#54]
<a href="https://github.com/alex"><img src="https://avatars.githubusercontent.com/u/772?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alex](https://github.com/alex)**
_Tuesday Nov 10, 2015 at 18:57 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/322_

----

On https://www.vets.gov/veterans-employment-center/

<img width="514" alt="screen shot 2015-11-10 at 1 57 06 pm" src="https://cloud.githubusercontent.com/assets/772/11072237/f1bd703c-87b2-11e5-9e55-d8f192868092.png">

The "TM" is a different font, and it sticks out a bit.

**Comment by MarinaMartin** [comment]
@emilyville I think this is fixed and can be closed?

**Comment by ayaleloehr** [comment]
Removing the TMs in this repo and one will still exist in the vets-website repo.
